server:
  port: 8081
spring:
  redis:
    host: 121.40.88.133
    port: 6379
    password: han4318233
    lettuce:
      pool:
        # 连接池最大等待时长(默认)
        max-wait: -1ms
        # 最大空闲连接数(默认)
        max-idle: 8
        # 最小空闲连接数(默认)
        min-idle: 0
        # 最大活动连接数(默认)
        max-active: 8


