version: '3'
services:
  zookeeper0:
    image: 'confluentinc/cp-zookeeper:latest'
    container_name: zookeeper0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka0:
    image: 'confluentinc/cp-kafka:latest'
    hostname: kafka0
    container_name: kafka0
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      # 访问地址
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # 复制因子
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Zookeeper 的访问地址
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181
      # 匿名且不加密的访问
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper0
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:9092
    depends_on:
      - kafka0