server:
  port: 8081
  servlet:
    context-path: /
spring:
  profiles:
#    active: shardingDataBase #分库分表
#    active: mysqlProxy #读写分离
    active: shardingTable #水平分表
#    active: dev # 单库单表操作
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.entity


