# 数据分片应用于单库分表操作
spring:
  shardingsphere:
    datasource:
      names: db1
      db1: # 数据库
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.40.88.133:3306/jiedu?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: root

    sharding:
      tables:
        user_info:
        # 配置表的分布，表的策略
          actual-data-nodes: db1.user_info$->{1..2}
          # 指定user_info表 主键id 生成策略为 SNOWFLAKE
          key-generator:
            column: id
            type: SNOWFLAKE
          # 指定分片策略
          table-strategy:
            inline:
                #根据年龄插入不同的表，如果年龄大于15岁插入user_info1表，如果年龄小于或等于15插入user_info2表
                sharding-column: age
                algorithm-expression: user_info$->{age>15?1:2}
                #约定id值是偶数添加到user_info1表，如果id是奇数添加到user_info2表
  #                sharding-column: id
  #                algorithm-expression: user_info$->{id%2+1}
    props:
      # 打开sql输出日志
      sql:
        show: true





